name: Executable Build

on:
  push:
    branches: [ "main" ]
    paths:
      - '*.py'
      - '.github/workflows/build.yaml'


jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          architecture: 'x64'
          cache: 'pip'
          cache-dependency-path: |
            **/requirements*.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Executable with Nuitka
        uses: Nuitka/Nuitka-Action@main
        with:
          company-name: "RedTTG"
          product-name: "ADB Wireless Helper"
          product-version: "1.0"
          script-name: main.py
          standalone: true
          onefile: true
          onefile-tempdir-spec: "adb-wireless-helper"
          deployment: true
          disable-console: false
          windows-icon-from-ico: icon/icon.ico

      - name: Setting up files
        run: |
          mkdir -p zipped
          cp build/main.exe zipped/main.exe
        shell: bash

      - name: Zip dist
        run: |
          python -c "import zipfile,shutil; shutil.make_archive('dist', 'zip', 'dist')"

      - name: Zip onefile
        run: |
          python -c "import zipfile,shutil; shutil.make_archive('onefile', 'zip', 'zipped')"

      - name: Update release
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            build/*.exe
            onefile.zip
            dist.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: latest
          name: Automatic Build
          body: Windows ADB Wireless Helper by RedTTG
          prerelease: false
          allowUpdates: true
